Спринт 11№
m3Rzy/java-filmorate pull request #8
Opened 2023-08-17 19:06 UTC by m3Rzy

2023-08-17 20:06 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-08-17 20:06 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +    public Genre mapRowToGenre(ResultSet resultSet, int rowNum) throws SQLException {
Подобные методы не должны быть публичными

2023-08-17 20:06 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public List<Film> getRating(int count) {
`count` -> `limit`

2023-08-17 20:06 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        String query = "UPDATE films SET " +
Запросы должны быть параметризированными.

Поищи `jdbctemplate параметризированный запрос`

2023-08-17 20:06 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            film.setGenres(genreDbStorage.findGenresForCurrentFilm(film.getId()));
Тут нужно быть аккуратнее!

Вот так в лоб нельзя делать в данном случае!
Давай поясню...
пусть у нас есть 100 фильмов... а у каждого из них есть жанры
для того чтобы собрать всё в одно и отдать при запросе нам нужно:

- достать все фильмы
- и все жанры к ним

Если делать "в лоб" то приходиться к каждому из 100-а фильмов отдельным запросом доставать еще и жанры...
получается ОДИН запрос на получение всех 100 фильмов и еще 100 запросов чтобы к каждому фильму подтянуть жанры....

Это называется проблема `N+1`
Чтобы её избежать мы должны заморочиться и в итоге приходим к всего ДВУМ запросам, вместо 101 !

Первый запрос на все фильмы, второй на все жанры для этих фильмов.

И все эти манипуляции следует выполнять в сервисе.

2023-08-17 20:06 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreStorage.java
> +    List<Genre> findGenres();
Методы не висят в воздухе!
Поэтому нет нужды в них повторять название сущности, например: `genreStorage.findGenres()`

Получается масло-масляное!
Лучше: `genreStorage.findAll()` `userService.findById()`

2023-08-17 20:06 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreStorage.java
> +    Genre findGenreById(int genreId);
При выборке одиночных объектов из хранилища, полезно использовать Optional.

Это поможет писать удобный код в функциональном стиле в сервисах и с него удобно начать погружение в мир функциональщины.

`Optional<Genre> findGenreById()`

2023-08-18 22:27 UTC, m3Rzy commented on src/main/resources/application.properties
> +spring.sql.init.mode=always
Не понимаю коммент, почему .properties не подходит?

2023-08-18 22:27 UTC, m3Rzy commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +import java.util.stream.Collectors;
Не понял коммент, классы InMemory в целом больше не будем использовать, удаляем?

2023-08-19 00:42 UTC, m3Rzy commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        String query = "UPDATE films SET " +
Коммент не совсем понял. В метод передаю готовый объект, откуда как раз можем брать параметры. И ведь ниже в методе идёт работа с ними.

2023-08-19 00:43 UTC, m3Rzy commented on src/main/java/ru/yandex/practicum/filmorate/service/genre/GenreService.java
> +        return genreDbStorage.findGenreById(genreId);
В сервисы по жанрам написал только те, которые используются. По остальным классам поправил хранилища и сервисы.

2023-08-19 00:45 UTC, m3Rzy commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            film.setGenres(genreDbStorage.findGenresForCurrentFilm(film.getId()));
Я так понял: можно написать 2 запроса с JOIN'ми, но дальше хз как их объединить в методе и работать с ними, так как ещё ведь их надо сопоставить между собой. Качественное решение я нашёл только с помощью Hibernate, но здесь его использование задание не подразумевает.

2023-08-19 18:11 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +import java.util.stream.Collectors;
Да, зачастую, уже на этом этапе их удаляют.

2023-08-19 18:41 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-08-19 18:41 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +            filmValidation(film);
1. Ничего не поменялось - ты делаешь валидацию в сервисе, а надо в контроллере.
2. Приватные методы должны располагаться ниже публичных

2023-08-19 18:41 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +        } catch (RuntimeException e) {
По работе самого метода.
- не нужно `try/catch`
- не нужно возвращать Optional у методов действий. Можно чтобы update вообще был `void` - т.е он или выполнится успешно или упадет, а ошибка будет перехвачена.

Вот так, например можно воспользоваться `Optional` и методом `finById`

```
    public Film updateFilm(Film film) {
        filmStorage.findById(film.getId())
                   .orElseThrow(() -> new NotFoundException("PUT - Фильма с id " + film.getId() + " не существует."));

        filmStorage.update(film);
        log.info("Фильм {} успешно изменён.", film);
        
        return film;
    }
```

Но можно и создать специальный метод `boolean isExist / isNotExist` и использовать его в сервисах

2023-08-19 18:41 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +            return filmStorage.findById(id).get();
Воспользуйся примером, приведенным в методе update  - перепиши код тут.

- не должно быть `try/catch`
- лог  NotFoundException сделай более подробным - какой такой фильм не найден??
- напиши код в одну строку - т.е. сразу начни метод с `return ....`

2023-08-19 18:41 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +            log.info("Фильм {} был успешно найден с помощью id.", filmStorage.findById(id));
filmStorage.findById(id) - Зачем же ты в логгере прям вызов метода сделал... У тебя же теперь улетел лишний запрос в базу! Аккуратнее с этим.

2023-08-19 18:41 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        но здесь его использование задание не подразумевает. */
Да, Hibernate не используем. Собираем все вручную.

Не нужно объединять их здесь!

Это хранилище фильмов - оно должно дать тебе фильмы.
Жанры для фильмов нужно получить у хранилища жанров. Должен появится метод принимающий все фильмы которые ты достал и выгребающий одним запросом для них жанры.
Потом ты распихиваешь их по фильмам кодом.

Комбинировать эту логику нужно в сервисе, оперируя разными хранилищами.

2023-08-19 18:45 UTC, FanaticFiz commented on src/main/resources/application.properties
> +spring.sql.init.mode=always
Подходит. Работает.
Но в реальных проектах так уже не пишут, есть YAML формат.
Я рекомендую всем переходить на него и привыкать к нему.

2023-08-19 18:49 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        String query = "UPDATE films SET " +
Нужно использовать NamedParameterJdbcTemplate
https://docs.spring.io/spring-framework/reference/data-access/jdbc/core.html#jdbc-NamedParameterJdbcTemplate

Сейчас сервис подвержен  SQL Injection
https://habr.com/ru/articles/148151/

2023-08-19 19:58 UTC, m3Rzy commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +        } catch (RuntimeException e) {
Я пробовал делать их void'ми, но тогда тесты из Postman будут завалены, поэтому методы возвращают либо объекты, либо исключения. 
![image](https://github.com/m3Rzy/java-filmorate/assets/79169826/9fe2ad58-964c-4f9b-8a0c-3671ecce1161)

2023-08-19 21:59 UTC, m3Rzy commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        но здесь его использование задание не подразумевает. */
Переделал как просто select * from, сейчас через Postman вижу, что всё цепляется 1-им запросом. 
![image](https://github.com/m3Rzy/java-filmorate/assets/79169826/a26468de-e444-4eeb-85ed-17eebca17f82)

2023-08-20 05:24 UTC, FanaticFiz approved these changes

2023-08-20 05:24 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Optional<Film> getFilmById(@PathVariable Integer id) {
Optional<Film> - не нужно выносить аж до контроллера.

Смотри смысл же в чем - у нас есть неопределенность есть объект или нет - но только на уровне базы данных. Поэтому в dao у нас метод возвращает `Optional<Film>`.
Уже в сервисе мы "раскрываем" Optional и если объекта нет, то кидаем исключение.
И все дальше из сервиса уже объект `Film getFilmById`

2023-09-01 23:47 UTC, merged